### ISSUE TITLE
Author Information

### ISSUE THREAD

**Issue by muppet2011ad** [nikhilwoodruff/CompSciApplications#11]
Since we have to add author information to each other's page, I thought it would be worth creating a place where we can leave our info for other people to write up (presumably we will make a footer for this - perhaps we can discuss how we're going to write it to ensure consistency).

---

To start with, here are the links to my linkedin and github profiles:

* https://github.com/muppet2011ad
* https://www.linkedin.com/in/james-townsend-54a48a195/

**Comment by nikhilwoodruff** [comment]
Yep, we should figure out a template; my GitHub is https://github.com/nwoodruff149 and LinkedIn is https://www.linkedin.com/in/nikhil-woodruff-759885167

**Comment by muppet2011ad** [comment]
All footers are now present
