### ISSUE TITLE
index.html needs to be started

### ISSUE THREAD

**Issue by muppet2011ad** [nikhilwoodruff/CompSciApplications#6]
The main page, *index.html*, is currently just some boilerplate HTML and a body that makes no sense in the context. It needs to be populated with links and a bit of filler content so it looks legit.

**Comment by fox8090** [comment]
We’ll get there man. We can wack the meet the team section on there

On 5 Nov 2019, at 14:39, James <notifications@github.com<mailto:notifications@github.com>> wrote:


The main page, index.html, is currently just some boilerplate HTML and a body that makes no sense in the context. It needs to be populated with links and a bit of filler content so it looks legit.

**Comment by muppet2011ad** [comment]
That's grand - I may well start fleshing it out later. I'm just putting stuff on github issues so that we can keep a "todo" list and tick things off.

**Comment by fox8090** [comment]
lovely stuff
